# -*- coding: utf-8 -*-
"""Server.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aMqCOeRJST5FWPV-xSQPO_9M9pTjcbaX
"""

#!/usr/bin/env python3
from your_package.srv import Sum, SumResponse
import rospy

def server_callback(req):
    print("Hi, My name is Chayanin Lawanrattanakul")
    return SumResponse

def sum_server():
    rospy.init_node('server')
    s = rospy.Service('sum', Sum, server_callback)
    print("Ready to.")
    rospy.spin()

if __name__ == "__main__":
    sum_server()

#!/usr/bin/env python3
from your_package.srv import Sum, SumResponse
import rospy

def user_sum():
    rospy.wait_for_service('empty')
    try:
        sum = rospy.ServiceProxy('empty', Sum)
        print("Please for me.")
        resp1 = sum(1,2)
        print(resp1)
    except rospy.ServiceException as e:
        print("Service call failed: %s"%e)

if __name__ == "__main__":
    user_sum()