# -*- coding: utf-8 -*-
"""Topic

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qCDccIbL-a0xqS7qY6s32M28Nk9sWPg2
"""

#!/usr/bin/env python3
import rospy
from your_package.msg import Data
def talker():
    pub = rospy.Publisher('chatter', Data, queue_size=10)
    rospy.init_node('talker', anonymous=True)
    rate = rospy.Rate(10) # 10hz
    while not rospy.is_shutdown():
        name = '6352500463'
        id = 10
        pub_data = Data(name=name, id=id)
        rospy.loginfo(pub_data)
        pub.publish(pub_data)
        rate.sleep()
if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass

#!/usr/bin/env python3
import rospy
from your_package.msg import Data
def callback(data):
    rospy.loginfo(rospy.get_caller_id() + " Name: %s, ID: %i", data.name, data.id)
def listener():
    rospy.init_node('listener', anonymous=True)
    rospy.Subscriber("chatter", Data, callback)
    rospy.spin()

if __name__ == '__main__':
    listener()